### ISSUE TITLE
test workflow for externally suggested websites 

### ISSUE THREAD

**Issue by vecna** [vecna/invi.sible.link#1]
Use case:

- [ ] a person has a list of website
- [ ] they have to be added as subject configure: https://invi.sible.link/subjects
- [ ] they have to be schedule every night of [this new list about Propaganda website](http://www.sharecsv.com/s/75edce68199ef9726636e8c365eff54a/Propaganda%20Network_%20IPs%20-%20Sheet6.csv) 
- [ ] test the three API used in the current homepage for the Brazil test

**Comment by lupa18** [comment]
https://invi.sible.link/subjects is a broken link :smile:

**Comment by vecna** [comment]
Yep @lupa18, I discontinued that API, was not really useful. At the moment there is a suite of tools who take a CSV file as option and schedule the execution of that list.

List example: https://github.com/vecna/chuptrex/blob/master/clinics-BR.csv
